### PR TITLE
go is not java

### PR DESCRIPTION
**Pull request by Stebalien**

### CODE REVIEW

**Comment by Stebalien** [comment]
😒

**Comment by dirkmc** [comment]
😭

**Comment by whyrusleeping** [comment]
haha, @dirkmc are you historically a java programmer?

**Comment by dirkmc** [comment]
My secret shame :)

**Comment by dirkmc** [comment]
@Stebalien @vyzo Thinking about this a little more.. should the `ValidationRecord`'s fields be copies of the originals, so that the validator function cannot corrupt the record's value (accidentally or on purpose)? Right now I believe it's possible for a validator function to do this:
```
func BadValidatorFunc(r *ValidationRecord) error {
    copy(r.Value, myBadData)
}

// ...

fmt.Printf("Good record value:\n", string(r.GetValue()))
err = validator.VerifyRecord(r)
fmt.Printf("Corrupted record value:\n", string(r.GetValue()))
datastore.Put(r)
```
Not sure if that's being too paranoid? It might also be worth making `PublicKeyValidator` immutable, and `ValidChecker`'s `Func` and `Sign` fields immutable, so that it's not possible to do
```rec.PublicKeyValidator.Func = myMaliciousFunc```

**Comment by dirkmc** [comment]
Here's a test case:
```
func TestValidatorRecordCorruption(t *testing.T) {
	sk, _, err := ci.GenerateKeyPairWithReader(ci.RSA, 1024, u.NewSeededRand(10))
	if err != nil {
		t.Fatal(err)
	}

	val := []byte("my val")
	r, err := MakePutRecord(sk, "/corrupt/validator", val, false)
	if err != nil {
		t.Fatal(err)
	}

	validator := make(Validator)
	corruptrc := &ValidChecker{
		Func: func(r *ValidationRecord) error {
			r.Value[0] = 'A'
			return nil
		},
		Sign: false,
	}
	validator["corrupt"] = corruptrc

	err = validator.VerifyRecord(r)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Compare(val, []byte("my val")) != 0 {
		t.Fatal("Validator does not prevent record value corruption")
	}
}
```

**Comment by vyzo** [comment]
I think that's a bit excessively paranoid and would require some very ungo-like code. And then where to stop?

**Comment by Stebalien** [comment]
Yeah, that's why I said "go is not java". In Java, you'd worry about that. In go, you just assume. Now, if we were using rust, you could *enforce* it but we're not...

**Comment by dirkmc** [comment]
I feel like this project needs more Enterprise JavaBeans™

**Pull request merged**
